### ISSUE TITLE
Cannot set empty value in datepicker's input, instead shows today's date even when value is set to empty string

### ISSUE THREAD

**Issue by prakash-2021** [puncoz-official/nepali-datepicker-reactjs#32]
My current implementation:
```ts
        <NepaliDatePicker
            inputClassName="form-control"
            className="ss-nepali-date"
            value={""} // <- I am setting this empty string but it shows today's date
            onChange={(value: string) => setPaidDate(value)}
            options={{ calenderLocale: "ne", valueLocale: "en" }}
          />
```

**Comment by puncoz** [comment]
thank you for reporting... this is a bug that needs to be fixed. Will look into this on the weekend, sorry for the inconvenience. Meanwhile, if you can create a PR, that will be helpful.

**Comment by puzan43382** [comment]
When will this issue be solved? Need to solve asap.

**Comment by rajivchaulagain** [comment]
@puncoz in code I found like it was setting the defaut as new date in the useEffect 
```
  useEffect(() => {
            setDate(toEnglish(value || ADToBS(new Date())))
    }, [value])
```
here, the or statement always adds up the default value if we set the value from parent to empty string. so I think new Date should be removed and let parent component handle the default state.

**Comment by puncoz** [comment]
Thank you @rajivchaulagain  again for this investigation. If you're interested in contributing, could you please do the following to fix this:

1. Add a prop `todayIfEmpty` with a default value `false`.
2. If this prop is true, set today's date.
2. else, set nothing.

Please implement this and send a pull request.

**Comment by rajivchaulagain** [comment]
@puncoz the above code u provided didn't worked as if the date is set to empty string("") then , the calendar is not opening as in below image
<img width="1415" alt="image" src="https://github.com/puncoz-official/nepali-datepicker-reactjs/assets/82865638/6d1e0b85-170f-4642-81df-f4ba0e599b26">

**Comment by puncoz** [comment]
@rajivchaulagain hmm, then we need to look further into how it's implemented when the value is empty. Specifically, when opening the calendar onClick, if the date value is empty, today's date should be passed to the calendar internally.

**Comment by aj3sh** [comment]
I am wondering why this issue is still open 🤔. I am facing the same issue. Some inputs can be optional and need to be empty.
