### ISSUE TITLE
Couldn't install this package

### ISSUE THREAD

**Issue by surajkhanal** [puncoz-official/nepali-datepicker-reactjs#36]
Tried to install and it throws 

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   dev react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from nepali-datepicker-reactjs@1.1.5
npm ERR! node_modules/nepali-datepicker-reactjs
npm ERR!   nepali-datepicker-reactjs@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See C:\Users\Dell\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Local\npm-cache\_logs\2024-03-05T03_54_45_903Z-debug-0.log
```

**Comment by rajivchaulagain** [comment]
I think react version 16.8.0 is not supported for this package use  react version of  "react": "^18.2.0" hence it works in this library.

**Comment by rajivchaulagain** [comment]
@puncoz can i contribute?

**Comment by puncoz** [comment]
@rajivchaulagain yeah sure, why not 👍

**Comment by rajivchaulagain** [comment]
@puncoz 
 ```
 "peerDependencies": {
        "react": "^18.2.0"
    },
```
Here the peer dependencies is making this error as it aspect the react version to be newer or to 18.2.0. @surajkhanal is trying to use this in slightly older version which doesn't meet the peerDependencies. One way is to degrade the peerDependencies like allowing for lower version of react or using else case for now.
like   
 ```
 "peerDependencies": {
        "react": "^16.8.0 || ^18.0.0"
    },
```

and for @surajkhanal you can use following cmd as 
npm i nepali-datepicker-reactjs --legacy-peer-deps

**Comment by puncoz** [comment]
Thank you, @rajivchaulagain , for this investigation. Before implementing these changes, we must confirm whether it works with React v16. Could you please try running this package in v16? If it works, please create a pull request and contribute.
