### ISSUE TITLE
'string' is not defined  no-undef

### ISSUE THREAD

**Issue by Laxman980** [puncoz-official/nepali-datepicker-reactjs#45]
import { NepaliDatePicker } from "nepali-datepicker-reactjs"
import "nepali-datepicker-reactjs/dist/index.css"
export default function Creatpost()

{
const [date, setDate] = useState<string>("")
}
<NepaliDatePicker inputClassName="form-control"
                              className=""
                              value={date}
                              onChange={(value: string) => setDate(value)}
                              options={{ calenderLocale: "ne", valueLocale: "en" }} />

**Comment by puncoz** [comment]
hi @Laxman980, it seems you are working with javascript. So, please remove all type definitions and it should work. In above code there is type defined in `onChange={(value: string) => setDate(value)}` it should be `onChange={(value) => setDate(value)}`

Sample working code for JavaScript: 
```js
import React, { useState } from "react"
import { NepaliDatePicker } from "nepali-datepicker-reactjs"
import "nepali-datepicker-reactjs/dist/index.css"

const App = () => {
    const [date, setDate] = useState("")

    return (
        <form>
            <label htmlFor="date">Date</label>
            <NepaliDatePicker inputClassName="form-control"
                              className=""
                              value={date}
                              onChange={(value) => setDate(value)}
                              options={{ calenderLocale: "ne", valueLocale: "en" }} />
        </form>
    )
}

export default App
```
