### ISSUE TITLE
Got Warning While adding Nepali Date Picker

### ISSUE THREAD

**Issue by sanjay-np** [puncoz-official/nepali-datepicker-reactjs#52]
Hey there
I am using this package for the date field. After using this package I got the warning message below.
![Screen Shot 2024-10-11 at 9 44 17 PM](https://github.com/user-attachments/assets/3e9265a9-872a-49d2-a54e-08bbda9e80ee)
![Screen Shot 2024-10-11 at 9 44 41 PM](https://github.com/user-attachments/assets/006d58d5-2f94-49a9-a1b4-9bea057e5d29)

I am using react ver 18.2.0 with vite ver 5.0.

**Comment by puncoz** [comment]
Thank you for reporting this. It will be fixed in a future update release.
