### ISSUE TITLE
Got Uncaught TypeError: months[currentLocale] / weeks[currentLocale] is undefined while changing the option props value

### ISSUE THREAD

**Issue by sanjay-np** [puncoz-official/nepali-datepicker-reactjs#53]
Hi there, 
I got  the error 
Uncaught TypeError: months[currentLocale] / weeks[currentLocale] is undefined
while changing the value of  
options->calenderLocale to "np",
options->valueLocale to "np".
Here is the code I have used for nepali date picker
```
<NepaliDatePicker
                    inputClassName="w-full focus:outline-none"
                    className='border rounded py-1.5 px-3 text-gray-600'
                    value={data?.date}
                    onChange={(value) => setData('date', value)}
                    options={{ calenderLocale: "np", valueLocale: "np" }} 
/>
```
Screenshot of the error:
![Screen Shot 2024-10-11 at 10 05 50 PM](https://github.com/user-attachments/assets/06e71d3b-679a-43a4-ab34-39921889acf9)

**Comment by puncoz** [comment]
hi @sanjay-np thank you for reporting this.

As per [ISO 639](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes#:~:text=Nepali-,ne,-nep), the correct locale code for the Nepali language is "**ne**," not "np" Please use "**ne**" accordingly.

Additionally, our package should handle invalid locale codes appropriately. I will ensure that it throws a proper error when an invalid locale code is passed as props in future update.
